theme = "onedark"

[editor]
cursorline = true
true-color = true
bufferline = "multiple"
color-modes = true

[editor.statusline]
left = ["mode", "spinner", "file-name", "read-only-indicator", "file-modification-indicator","version-control"]
right = ["selections", "separator", "position", "separator", "file-encoding", "file-line-ending", "separator", "file-type"]
separator = "│"

[editor.whitespace]
render = "all"

[editor.indent-guides]
render = true
