[[language]]
name = "c"
language-id = "c"
scope = "source.c"
language-servers = ["clangd"]

[[language]]
name = "rust"
scope = "source.rust"
roots = ["Cargo.lock"]
language-servers = ["rust-analyzer"]

[[language]]
name = "toml"
auto-format = true
language-servers = ["taplo"]
formatter = { command = "taplo", args = ["fmt", "-"] }

[[language]]
name = "python"
auto-format = true
language-servers = ["pylsp"]

[language-server.pylsp.config.pylsp]
plugins.black.enabled = true
